<footer class="bg-dark text-white py-4">
    <div class="container">
        <p class="text-center mb-3"> 2026 Practica Thomy. Todos los derechos reservados.</p>
        <nav>
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a href="/privacy" class="nav-link text-white">Política de Privacidad</a>
                </li>
                <li class="nav-item">
                    <a href="/terms" class="nav-link text-white">Términos y Condiciones</a>
                </li>
                <li class="nav-item">
                    <a href="/contact" class="nav-link text-white">Contacto</a>
                </li>
            </ul>
        </nav>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>

</html>