<section>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Talle</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($ropas as $ropa) { ?>
                <tr>
                    <td><?= $ropa->ropa_id ?></td>
                    <td><?= $ropa->nombre ?></td>
                    <td><?= $ropa->nombre_talle ?></td>
                    <td>$<?= $ropa->precio ?></td>
                    <td class="d-flex align-items-center gap-2">
                        <a href="view-edit-ropa/<?= $ropa->ropa_id ?>" class="btn btn-primary">Editar</a>
                        <form action="delete" method="POST">
                            <input type="hidden" name="ropa_id" value="<?= $ropa->ropa_id ?>">
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</section>
<section>
    <h4>Agregar</h4>

    <form action="add-ropa" method="post">
        <div>
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" required>
        </div>
        <div>
            <label for="talle_id" class="form-label">Talle</label>
            <?php
            require 'app/template/seleccion-talles.phtml'; ?>
        </div>
        <div>
            <label for="precio" class="form-label">Precio</label>
            <input type="number" step="0.01" class="form-control" id="precio" name="precio" required>
        </div>

        <button class="btn-aesthetic-mono">
                ENVIAR
        </button>


    </form>
</section>